// Generated by CoffeeScript 1.9.2
(function() {
  'use strict';
  define(['angular', 'lodash', 'md5'], function(ng, _) {
    return ng.module('CryptoJS', []).service('md5', function() {
      return function(input) {
        var s;
        if (_.isObject(input)) {
          s = JSON.stringify(input);
        } else {
          s = input;
        }
        return (CryptoJS.MD5("" + s)).toString();
      };
    });
  });

}).call(this);
