// Generated by CoffeeScript 1.9.2
(function() {
  'use strict';
  define(function() {
    return function($scope, modalStateModel, mvModalService, options, stateNamePrefix) {
      var actionName, capitalize, fn, optionValue;
      capitalize = function(s) {
        return s[0].toUpperCase() + s.slice(1);
      };
      fn = function(actionName, optionValue) {
        var stateName;
        stateName = stateNamePrefix + capitalize(actionName);
        if (!modalStateModel.hasState(stateName)) {
          modalStateModel.onModalStateChange(stateName, function() {
            return mvModalService.openModal(optionValue);
          });
        }
        return $scope[actionName] = function(data) {
          return modalStateModel.changeState(stateName, data);
        };
      };
      for (actionName in options) {
        optionValue = options[actionName];
        fn(actionName, optionValue);
      }
      return $scope.result = function() {
        return mvModalService.result();
      };
    };
  });

}).call(this);
