// Generated by CoffeeScript 1.9.2
(function() {
  define(['angular', '_requirejs-paths'], function(ng) {
    console.log('Loading packages');
    require(['app/main', 'browse/main', 'login/main'], function() {
      console.log('Bootstrapping app');
      require(['domReady'], function(document) {
        var injector;
        injector = ng.bootstrap(document, ['mvWebUi'], {
          strictDi: true
        });
      });
    });
  });

}).call(this);
