// Generated by CoffeeScript 1.9.2
(function() {
  define(function() {
    requirejs.config({
      paths: {
        'app': '/packages/app/scripts',
        'login': '/packages/login/scripts',
        'browse': '/packages/app/features/browse/scripts',
        'uibootstrap': '/bower_components/angular-bootstrap/ui-bootstrap-tpls'
      }
    });
  });

}).call(this);
