# Auto Generated by 'grunt installPackages' task - do not edit
# Last Generated: Tue, 21 Jul 2015 08:18:32 GMT
#
# Copyright � 2014 VRX Studios Inc.
# All Rights Reserved

define ()->
  requirejs.config
    paths:
      'app': '/packages/app/scripts'
      'login': '/packages/login/scripts'
      'browse': '/packages/app/features/browse/scripts'
      'uibootstrap':'/bower_components/angular-bootstrap/ui-bootstrap-tpls'
  return
