// Generated by CoffeeScript 1.9.2
(function() {
  'use strict';
  define(['angular', 'lodash', 'core/config', 'core/myalert', 'core/app', 'core/routerConfig', 'core/constants-main', 'core/controllers-main', 'core/directives-main', 'core/models-main', 'core/services-main'], function(ng, _, Config, myAlert) {
    ng.module('mvWebUi').constant('Config', Config).run([
      'Restangular', 'Config', function(Restangular, Config) {
        Restangular.setBaseUrl(Config.api);
        return Restangular.setDefaultHeaders({
          'Content-Type': 'application/json'
        });
      }
    ]);
    require(['core/_packageloader']);
  });

}).call(this);
