// Generated by CoffeeScript 1.9.2
(function() {
  define(['angular', 'core/directives/mv-modal', 'core/app'], function(ng, createModalDirective) {
    ng.module('mvWebUi.directives').directive('mvModal', ['$injector', createModalDirective]);
  });

}).call(this);
