// Generated by CoffeeScript 1.9.2
(function() {
  define(['angular', 'core/models/modal', 'core/app'], function(ng, ModalStateModel) {
    ng.module('mvWebUi.data').service('modalStateModel', ModalStateModel);
  });

}).call(this);
