//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public  class Ticket : BaseEntity
    {
        public Ticket()
        {
            this.TicketConversations = new HashSet<TicketConversation>();
        }
    
        [Key]
        public System.Guid ID { get; set; }

        public System.Guid? UserID { get; set; }
        [ForeignKey("UserID")]
        public virtual Account User { get; set; }

        public int TicketNumber { get; set; }
        [StringLength(10)]
        public string Status { get; set; }
        [StringLength(20)]
        public string Priority { get; set; }
        [StringLength(1000)]
        public string Subject { get; set; }
       
        [StringLength(10)]
        public string TicketType { get; set; }
        
        [StringLength(500)]
        public string Domain { get; set; }
        [StringLength(20)]
        public string Department { get; set; }

        [StringLength(100)]
        public string UserCommunicationEmail { get; set; }
       
        
        //[StringLength(20)]
        //public string ContactNumber { get; set; }
        //[StringLength(50)]
        //public string LastReplier { get; set; }
        //[StringLength(50)]
        //public string UserName { get; set; }

        public virtual ICollection<TicketConversation> TicketConversations { get; set; }
        
    }
}
