// Generated by CoffeeScript 1.9.2
(function() {
  define(function() {
    return function(s) {
      if (s) {
        return s[0].toUpperCase() + s.slice(1);
      } else {
        return '';
      }
    };
  });

}).call(this);
