// Generated by CoffeeScript 1.9.2
(function() {
  define(['core/util/make-observable', 'lodash'], function(makeObservable, _) {
    return function(name) {
      if (name == null) {
        name = 'anonymous event';
      }
      return function($log) {
        var _observable;
        _observable = makeObservable({
          event: function() {
            var base;
            if ($log != null) {
              $log.log("<" + name + "> raised at " + (typeof (base = new Date()).toISOString === "function" ? base.toISOString() : void 0));
            }
            if (arguments.length > 0 && (arguments[0] != null)) {
              return arguments[0];
            }
          }
        }, $log);
        return function(data, forwardFunction) {
          var isFunction;
          isFunction = _.isFunction(data);
          if (!(isFunction && !forwardFunction)) {
            return _observable.event(data);
          } else {
            return _observable.on('event', data);
          }
        };
      };
    };
  });

}).call(this);
