// Generated by CoffeeScript 1.9.2
(function() {
  'use strict';
  define(['core/util/assert', 'core/util/props', 'core/util/queue-set'], function(Assert, props, createQueueSet) {
    return function(capacity) {
      var obj, queueSet, theSet;
      Assert(capacity > 0, 'Capacity for LRU Set must be greater than 0');
      obj = Object;
      theSet = obj.create(createQueueSet());
      queueSet = obj.getPrototypeOf(theSet);
      return props(theSet, {
        capacity: {
          get: function() {
            return capacity;
          }
        },
        enqueue: {
          configurable: true,
          value: function(value) {
            if (!(this.length < capacity)) {
              this.dequeue();
            }
            return queueSet.enqueue(value);
          }
        },
        get: {
          configurable: true,
          value: function(key) {
            var val;
            val = queueSet.get(key);
            if (val != null) {
              queueSet.enqueue(val);
            }
            return val;
          }
        }
      });
    };
  });

}).call(this);
