// Generated by CoffeeScript 1.9.2
(function() {
  'use strict';
  define(['lodash', 'core/util/props', 'core/util/assert'], function(_, props, Assert) {
    return function() {
      var $$resources, _resources, theService;
      _resources = {};
      $$resources = function(k, v) {
        if (v != null) {
          return _resources[k] = v;
        } else if (k != null) {
          return _resources[k];
        } else {
          return void 0;
        }
      };
      return theService = props({}, {
        setLoginQuery: {
          value: function(query) {
            Assert.isObjectInstance(query, 'Expected object as login query definition');
            return props(theService, {
              login: {
                value: function(credentials) {
                  return theService.run(query.login(credentials));
                }
              }
            });
          }
        },
        run: {
          value: function(query) {
            return query();
          }
        },
        clear: {
          value: function() {
            var delKey;
            delKey = function(v, k) {
              return delete this[k];
            };
            _.forIn(this, _.bind(delKey, this));
            _resources = {};
          }
        },
        $$resources: {
          value: $$resources
        }
      });
    };
  });

}).call(this);
