// Generated by CoffeeScript 1.9.2
(function() {
  define(['lodash', 'core/util/assert'], function(_, Assert) {
    return function() {
      var args, createServiceConstructor, ctorDefinition, func;
      ctorDefinition = _.first(arguments);
      Assert["true"](!_.isUndefined(ctorDefinition, 'Service ctor not provided'));
      if (_.isArray(ctorDefinition)) {
        func = _.last(ctorDefinition);
        args = _.first(ctorDefinition, ctorDefinition.length - 1);
        createServiceConstructor = function(config) {
          var instanceArgs;
          instanceArgs = _.clone(args);
          instanceArgs.push(func(config));
          return instanceArgs;
        };
      } else {
        Assert["true"](_.isFunction(ctorDefinition, 'Provide either a function or an array with dependencies'));
        createServiceConstructor = ctorDefinition;
      }
      return function() {
        var serviceCtor;
        serviceCtor = createServiceConstructor(this);
        Object.defineProperty(this, '$get', {
          value: serviceCtor
        });
      };
    };
  });

}).call(this);
