// Generated by CoffeeScript 1.9.2
(function() {
  define(function() {
    var hasObserversListForState, notifyObservers;
    hasObserversListForState = function(observers, stateName) {
      return observers && observers.hasOwnProperty(stateName);
    };
    notifyObservers = function(observers, state, data) {
      var func, i, len, ref;
      if (hasObserversListForState(observers, state)) {
        ref = observers[state];
        for (i = 0, len = ref.length; i < len; i++) {
          func = ref[i];
          func(data);
        }
      }
    };
    return function() {
      var _modalState, _observers;
      _modalState = void 0;
      _observers = {};
      return {
        clear: function() {
          _modalState = void 0;
          return this;
        },
        get: function() {
          return _modalState;
        },
        hasState: function(stateName) {
          return _observers[stateName] != null;
        },
        changeState: function(state, data) {
          _modalState = state;
          notifyObservers(_observers, _modalState, data);
          return this;
        },
        onModalStateChange: function(stateName, action) {
          if (!hasObserversListForState(_observers, stateName)) {
            _observers[stateName] = [];
          }
          _observers[stateName].push(action);
          return this;
        }
      };
    };
  });

}).call(this);
